"""Project files read by more than one CLI, written once per run.

Every target CLI loads AGENTS.md; Copilot CLI, Codex and Antigravity also
load .agents/skills/, and Claude Code and Copilot both read the workspace
.mcp.json. Adapters declare
which of these their CLI consumes (``CliAdapter.shared_outputs``) and the
orchestrator calls :func:`deploy_shared_outputs` once for the union, so no
two adapters render the same file.

AGENTS.md size budget: Antigravity reads at most 24,000 bytes per rule file
and Codex stops after 32 KiB of project docs in total, and both truncate
silently. (Claude Code documents no cap.) The foundry block is therefore
capped at ``AGENTS_MD_BUDGET``:
rules are embedded in priority order while they fit, and the rest go to
``.agents/rules/foundry-<rule>.md`` (with Antigravity trigger frontmatter, so
it loads them natively) and are listed in AGENTS.md as pointers. Each rule
lands in exactly one of the two places, so no CLI reads a rule twice.

Ownership: .agents/ is a cross-vendor directory that other tools write to
too (Codex's Claude importer copies .claude/skills/ into .agents/skills/).
A name alone therefore doesn't prove the foundry wrote something, so every
file or skill directory the foundry writes there carries a marker, and the
prune passes only ever touch marked content.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from .adapters.base import AGENTS_MD, AGENTS_SKILLS, MCP_JSON, CliAdapter, Selections
from .convert import command_skill
from .deploy import (
    SKILL_COPY_IGNORE,
    _command_skill_parent,
    _owned_command_names,
    _owned_rule_names,
    _owned_skill_names,
    write_mcp_servers,
)
from .instructions import (
    claude_md_blockers,
    has_agent_foundry_header,
    merge_project_text,
    prepend_agent_foundry_header,
    project_text,
    render_env_commands,
    rule_description,
    update_agent_foundry_header,
)
from .paths import AGENT_FOUNDRY_MARKER_END, AGENT_FOUNDRY_MARKER_START, COMMANDS_DIR, REPO_ROOT
from .registry import CLAUDE_ONLY_RULES, MODULAR_RULES, PORTABLE_COMMANDS, PORTABLE_SKILLS

# Leaves room for the project's own AGENTS.md content under both the
# Antigravity (24,000 B/file) and Codex (32 KiB total) limits.
AGENTS_MD_BUDGET = 20_000

AGENTS_RULES_DIR = Path(".agents") / "rules"
AGENTS_SKILLS_DIR = Path(".agents") / "skills"

# Ownership markers (see module docstring). Overflow rules are namespaced
# `foundry-<rule>.md` so they never collide with a project's own rules.
_RULE_PREFIX = "foundry-"
_RULE_MARKER = ("<!-- agent-foundry: managed file, regenerated by setup.py — "
                "edit the foundry source rule instead -->")
_SKILL_MARKER_FILE = ".agent-foundry"

# Embed priority after the base rules: tooling first, templates last.
_MODULAR_PRIORITY = ("lang", "platform", "security", "templates")

# Claude-only SKILL.md frontmatter keys, dropped from the shared root:
# Copilot CLI has no `model` key, and `allowed-tools` names Claude tools.
_UNSUPPORTED_SKILL_FRONTMATTER = ("model", "allowed-tools")

# Claude-specific wording in skill markdown, rewritten for the shared root
# at deploy time so the Claude sources stay untouched: sibling skills live
# in .agents/skills/, and "invoke Skill(x)" becomes a pointer to that skill.
_SHARED_REWRITES = (
    (re.compile(r"\.claude/skills/"), ".agents/skills/"),
    (re.compile(r"`Skill\(([a-z][a-z0-9-]*)\)`"),
     r"the `\1` skill (`.agents/skills/\1/SKILL.md`)"),
    (re.compile(r"a short `AskUserQuestion` batch"), "one short batch of questions"),
)

# Codex injects at most this many bytes of an explicitly invoked SKILL.md
# (MAX_SKILL_PROMPT_BYTES, 0.156.1). Larger skills deploy as a short
# SKILL.md pointing at the unchanged text in SKILL.full.md.
_SKILL_PROMPT_LIMIT = 8_000
_FULL_SKILL = "SKILL.full.md"


@dataclass(frozen=True)
class _Rule:
    name: str             # rule filename, e.g. "python.md"
    category: str | None  # modular category, or None for a base rule
    body: str
    dest: str             # overflow path, e.g. ".agents/rules/foundry-python.md"


def portable_rules(sel: Selections) -> list[_Rule]:
    """Selected rules for non-Claude CLIs, in embed-priority order.

    Claude-only rules are dropped. A modular rule whose filename collides
    with an earlier rule overflows to ``foundry-<category>-<rule>``,
    matching the .claude/rules/ collision convention.
    """
    candidates: list[tuple[str, str | None, Path]] = [
        (rule, None, REPO_ROOT / "common" / "rules" / rule) for rule in sel.base
    ]
    extra = [c for c in sel.modular if c not in _MODULAR_PRIORITY]
    for category in (*_MODULAR_PRIORITY, *extra):
        candidates += [
            (rule, category, REPO_ROOT / "common" / "rule-library" / category / rule)
            for rule in sel.modular.get(category, [])
        ]
    rules: list[_Rule] = []
    used: set[str] = set()
    for name, category, src in candidates:
        if name in CLAUDE_ONLY_RULES or not src.is_file():
            continue
        filename = f"{category}-{name}" if name in used else name
        used.add(filename)
        rules.append(_Rule(name, category, src.read_text(encoding="utf-8").strip(),
                           (AGENTS_RULES_DIR / f"{_RULE_PREFIX}{filename}").as_posix()))
    return rules


_HEADING = re.compile(r"#{1,6}(?=\s)")
_FENCE = re.compile(r"\s*(```|~~~)")


def _demote_headings(body: str, levels: int = 2) -> str:
    """Shift a rule's markdown headings down ``levels`` so it nests under the
    block's ``##`` heading. Lines inside code fences are left alone."""
    lines, fence = [], None
    for line in body.split("\n"):
        if m := _FENCE.match(line):
            fence = None if fence == m.group(1) else fence or m.group(1)
        elif fence is None and (h := _HEADING.match(line)):
            line = "#" * min(6, len(h.group()) + levels) + line[h.end():]
        lines.append(line)
    return "\n".join(lines)


def _render_block(env: str, embedded: list[_Rule], pointers: list[_Rule]) -> str:
    sections = [AGENT_FOUNDRY_MARKER_START,
                "## Coding Standards (agent-foundry)",
                "",
                "These standards are managed by agent-foundry and apply to any "
                "CLI that reads `AGENTS.md`. Setup rewrites this block on every "
                "update — keep project-specific instructions outside it.",
                "",
                "### Environment",
                "",
                "```bash",
                env,
                "```",
                "",
                "### Project Docs",
                "",
                "- `codemaps/INDEX.md` — read before modifying unfamiliar modules; "
                "run the `update-codemaps` command after significant structural changes",
                "- `docs/ARCHITECTURE.md` (design decisions) and `docs/DEVELOPMENT.md` "
                "(setup and workflow), if present",
                ""]
    for rule in embedded:
        sections += [f"<!-- rule: {rule.name} -->", _demote_headings(rule.body), ""]
    if pointers:
        sections += ["### More rules", "",
                     "Read the matching file before working in its area:", ""]
        sections += [f"- `{rule.dest}` — {rule_description(rule.name)}" for rule in pointers]
        sections.append("")
    sections.append(AGENT_FOUNDRY_MARKER_END)
    return "\n".join(sections)


def render_agents_block(
    sel: Selections, budget: int = AGENTS_MD_BUDGET,
) -> tuple[str, list[_Rule]]:
    """Render the marker-wrapped AGENTS.md block within ``budget`` bytes.

    Returns the block and the rules that overflowed to .agents/rules/.
    Each rule is embedded if the block, with every later rule still counted
    as a pointer, stays within budget — so the final block always fits.
    """
    env = render_env_commands(sel.langs)
    rules = portable_rules(sel)
    embedded: list[_Rule] = []
    overflow: list[_Rule] = []
    for i, rule in enumerate(rules):
        candidate = _render_block(env, [*embedded, rule], [*overflow, *rules[i + 1:]])
        if len(candidate.encode("utf-8")) <= budget:
            embedded.append(rule)
        else:
            overflow.append(rule)
    return _render_block(env, embedded, overflow), overflow


def _rule_frontmatter(rule: _Rule) -> str:
    """Antigravity rule frontmatter: base rules always apply, language rules
    trigger on their file extensions, everything else on model decision."""
    extensions = MODULAR_RULES.get("lang", {}).get(rule.name, {}).get("detect", [])
    if rule.category is None:
        trigger = "trigger: always_on"
    elif rule.category == "lang" and extensions:
        globs = ", ".join(f"**/*{ext}" for ext in extensions)
        trigger = f"trigger: glob\nglobs: {json.dumps(globs)}"
    else:
        trigger = "trigger: model_decision"
    return f"---\n{trigger}\ndescription: {json.dumps(rule_description(rule.name))}\n---\n"


def _write_overflow_rules(project: Path, overflow: list[_Rule]) -> None:
    """Write overflow rules and remove foundry-marked ones no longer needed.
    Unmarked files (the project's own rules) are never touched."""
    rules_dir = project / AGENTS_RULES_DIR
    keep = {Path(r.dest).name for r in overflow}
    owned = _owned_rule_names()
    if rules_dir.is_dir():
        for existing in sorted(rules_dir.glob(f"{_RULE_PREFIX}*.md")):
            if existing.name in keep or existing.name.removeprefix(_RULE_PREFIX) not in owned:
                continue
            if _RULE_MARKER in existing.read_text(encoding="utf-8", errors="replace"):
                existing.unlink()
                print(f"  Removed stale foundry rule: {AGENTS_RULES_DIR.as_posix()}/{existing.name}")
    if not overflow:
        return
    rules_dir.mkdir(parents=True, exist_ok=True)
    for rule in overflow:
        (project / rule.dest).write_text(
            f"{_rule_frontmatter(rule)}{_RULE_MARKER}\n\n{rule.body}\n", encoding="utf-8")
    print(f"  {len(overflow)} rule(s) over the AGENTS.md budget → "
          f"{AGENTS_RULES_DIR.as_posix()}/: {', '.join(r.name for r in overflow)}")


def write_agents_md(
    project: Path, sel: Selections, limits: dict[str, int] | None = None,
    absorb_claude_md: bool = False,
) -> None:
    """Create or update the foundry block in AGENTS.md (+ rule overflow).

    ``limits`` maps a CLI's display name to the AGENTS.md bytes it reads;
    a file over any of them gets a warning, since the CLI truncates it.
    ``absorb_claude_md``: Claude Code is a target. It skips AGENTS.md while
    a CLAUDE.md exists, so CLAUDE.md's project text (everything outside its
    foundry header) moves into AGENTS.md, and CLAUDE.md is removed once
    AGENTS.md is written. The Claude adapter has already asked before this
    runs on a CLAUDE.md the foundry didn't write.
    """
    agents_md = project / "AGENTS.md"
    claude_md = project / "CLAUDE.md"
    absorb = absorb_claude_md and claude_md.is_file()
    same_file = absorb and agents_md.exists() and agents_md.samefile(claude_md)
    moved = ""
    if same_file and agents_md.is_symlink():
        # One file under both names (a common way to share it): it stays
        # as AGENTS.md alone, so a link named AGENTS.md becomes the file.
        text = agents_md.read_text(encoding="utf-8")
        agents_md.unlink()
        agents_md.write_text(text, encoding="utf-8")
    elif absorb and not same_file:
        moved = project_text(claude_md.read_text(encoding="utf-8"))
        if moved == f"# {sel.project_name}":
            moved = ""
    block, overflow = render_agents_block(sel, AGENTS_MD_BUDGET)
    if len(block.encode("utf-8")) > AGENTS_MD_BUDGET:
        print(f"  ⚠ The agent-foundry block is {len(block.encode('utf-8')):,} bytes, over its "
              f"{AGENTS_MD_BUDGET:,}-byte budget even with every rule as a pointer")
    if not agents_md.exists():
        agents_md.write_text(f"{moved or f'# {sel.project_name}'}\n\n{block}\n",
                             encoding="utf-8")
        print("  Created AGENTS.md")
    else:
        try:
            existing = agents_md.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            print("  ⚠ AGENTS.md isn't UTF-8 text — left unchanged (re-save it as UTF-8)")
            return
        content = merge_project_text(existing, moved, sel.project_name) if moved else existing
        if has_agent_foundry_header(content):
            agents_md.write_text(update_agent_foundry_header(content, block),
                                 encoding="utf-8")
            print("  Updated agent-foundry block in AGENTS.md")
        else:
            (project / "AGENTS.md.old").write_text(existing, encoding="utf-8")
            agents_md.write_text(prepend_agent_foundry_header(existing, block),
                                 encoding="utf-8")
            print("  Merged agent-foundry block into AGENTS.md "
                  "(original saved to AGENTS.md.old)")
    if absorb:
        claude_md.unlink()
        what = ("Moved CLAUDE.md into AGENTS.md" if moved
                else "Removed the CLAUDE.md link" if same_file
                else "Removed CLAUDE.md (it held only the agent-foundry header)")
        print(f"  {what} — Claude Code reads AGENTS.md only while no CLAUDE.md exists")
    if absorb_claude_md:
        for path in claude_md_blockers(project):
            shown = path.relative_to(project) if path.is_relative_to(project) else path
            print(f"  ⚠ Claude Code skips AGENTS.md while {shown} exists "
                  "— move its content into AGENTS.md and delete it")
    _write_overflow_rules(project, overflow)
    size = len(agents_md.read_bytes())
    for cli, limit in (limits or {}).items():
        if size > limit:
            print(f"  ⚠ AGENTS.md is {size:,} bytes — {cli} reads only the first "
                  f"{limit:,}; move project content from AGENTS.md into docs/")


def remove_agents_md(project: Path, project_name: str) -> None:
    """Take the foundry block (and its overflow rules) back out of AGENTS.md
    once no selected CLI reads it; the file goes too if only the stub the
    foundry created is left."""
    agents_md = project / "AGENTS.md"
    claude_md = project / "CLAUDE.md"
    if agents_md.is_symlink() or (agents_md.exists() and claude_md.exists()
                                  and agents_md.samefile(claude_md)):  # hard link too
        # Most likely → CLAUDE.md: its foundry block may be the Claude header,
        # and removing it would stop Claude Code updates. Never edit or
        # delete through the link.
        print("  AGENTS.md is a link — left it (and the file it points to) unchanged")
        _write_overflow_rules(project, [])
        return
    try:
        text = agents_md.read_text(encoding="utf-8") if agents_md.exists() else ""
    except UnicodeDecodeError:
        text = ""
    if has_agent_foundry_header(text):
        rest = update_agent_foundry_header(text, "").strip()
        if rest in ("", f"# {project_name}"):
            agents_md.unlink()
            print("  Removed AGENTS.md (no selected CLI reads it)")
        else:
            agents_md.write_text(rest + "\n", encoding="utf-8")
            print("  Removed the agent-foundry block from AGENTS.md (no selected CLI reads it)")
    _write_overflow_rules(project, [])


def _sanitize_skill_frontmatter(skill_md: Path) -> None:
    """Drop Claude-only frontmatter keys, including multi-line values
    (an indented block or `- item` list under the key)."""
    if not skill_md.exists():
        return
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return
    end = text.find("\n---", 3)
    if end == -1:
        return
    kept, dropping = [], False
    for line in text[:end].split("\n"):
        key = line.split(":", 1)[0].strip()
        if not line[:1].isspace() and not line.startswith("-"):
            dropping = ":" in line and key in _UNSUPPORTED_SKILL_FRONTMATTER
        if not dropping:
            kept.append(line)
    skill_md.write_text("\n".join(kept) + text[end:], encoding="utf-8")


def _rewrite_for_shared_root(skill_dir: Path) -> None:
    for md in skill_dir.rglob("*.md"):
        text = original = md.read_text(encoding="utf-8")
        for pattern, replacement in _SHARED_REWRITES:
            text = pattern.sub(replacement, text)
        if text != original:
            md.write_text(text, encoding="utf-8")


def _split_large_skill(skill_dir: Path) -> None:
    """Keep SKILL.md under Codex's injection limit (see _SKILL_PROMPT_LIMIT)."""
    skill_md = skill_dir / "SKILL.md"
    text = skill_md.read_text(encoding="utf-8")
    if len(text.encode("utf-8")) <= _SKILL_PROMPT_LIMIT:
        return
    end = text.find("\n---", 3) if text.startswith("---") else -1
    frontmatter = text[:end + 4] if end != -1 else ""
    (skill_dir / _FULL_SKILL).write_text(text, encoding="utf-8")
    skill_md.write_text(
        f"{frontmatter}\n\nThis skill's full instructions are in `{_FULL_SKILL}` in this "
        "directory — split out because some CLIs cut skill files at 8 KB. Read that "
        "file completely before doing anything else, then follow it.\n", encoding="utf-8")


def _claim_skill_dir(dest: Path) -> bool:
    """Clear ``dest`` for a fresh foundry copy. False if it's project-owned."""
    if dest.exists():
        if not (dest / _SKILL_MARKER_FILE).is_file():
            print(f"  Left project-owned {AGENTS_SKILLS_DIR.as_posix()}/{dest.name}/ "
                  "in place (foundry copy not deployed)")
            return False
        shutil.rmtree(dest)
    return True


def _mark_skill_dir(dest: Path) -> None:
    (dest / _SKILL_MARKER_FILE).write_text(
        "Managed by agent-foundry; regenerated by setup.py.\n", encoding="utf-8")
    print(f"  Deployed skill → {AGENTS_SKILLS_DIR.as_posix()}/{dest.name}/")


def remove_shared_skills(project: Path) -> None:
    """Prune every foundry skill from .agents/skills/ once no selected CLI
    reads the shared root (same ownership proof as deploying)."""
    skills_root = project / AGENTS_SKILLS_DIR
    if skills_root.is_symlink():
        print(f"  {AGENTS_SKILLS_DIR.as_posix()}/ is a symlink — left it unchanged")
        return
    owned = _owned_skill_names() | {Path(c).stem for c in _owned_command_names()}
    if skills_root.is_dir():
        for existing in sorted(skills_root.iterdir()):
            if (existing.name in owned and existing.is_dir()
                    and (existing / _SKILL_MARKER_FILE).is_file()):
                shutil.rmtree(existing)
                print(f"  Removed foundry skill: {AGENTS_SKILLS_DIR.as_posix()}/{existing.name}/ "
                      "(no selected CLI reads it)")
        if not any(skills_root.iterdir()):
            skills_root.rmdir()


def deploy_shared_skills(project: Path, sel: Selections) -> None:
    """Deploy the selected portable skills, plus portable Claude commands
    converted to skills, to .agents/skills/.

    Foundry-marked skill directories that are no longer wanted (or no
    longer portable) are removed. An unmarked directory is the project's
    own — even if it shares a foundry skill's name — and is left alone.
    """
    skills_root = project / AGENTS_SKILLS_DIR
    wanted = [s for s in sel.skills if s in PORTABLE_SKILLS
              and (REPO_ROOT / "cli" / "claude" / "skills" / s).is_dir()]
    # A skill's sub-commands (update-foundry-check → update-foundry) only
    # come along with their skill, as in .claude/commands/.
    commands = sorted(
        COMMANDS_DIR / c for c in PORTABLE_COMMANDS
        if (COMMANDS_DIR / c).is_file()
        and _command_skill_parent(Path(c).stem) in (None, *wanted))
    keep = set(wanted) | {c.stem for c in commands}
    # Pruning needs both proofs: a name the foundry ships (or shipped) and
    # the marker — a copy of a foundry skill under a new name keeps the
    # marker but is the project's.
    owned = _owned_skill_names() | {Path(c).stem for c in _owned_command_names()}
    if skills_root.is_dir():
        for existing in sorted(skills_root.iterdir()):
            if (existing.name not in keep and existing.name in owned and existing.is_dir()
                    and (existing / _SKILL_MARKER_FILE).is_file()):
                shutil.rmtree(existing)
                print(f"  Removed stale foundry skill: "
                      f"{AGENTS_SKILLS_DIR.as_posix()}/{existing.name}/")
    for name in wanted:
        dest = skills_root / name
        if not _claim_skill_dir(dest):
            continue
        shutil.copytree(REPO_ROOT / "cli" / "claude" / "skills" / name, dest,
                        ignore=SKILL_COPY_IGNORE)
        _adapt_skill_dir(dest)
    for command in commands:
        dest = skills_root / command.stem
        if not _claim_skill_dir(dest):
            continue
        dest.mkdir(parents=True)
        (dest / "SKILL.md").write_text(command_skill(command), encoding="utf-8")
        # A skill's sub-commands inherit its user-only policy.
        parent = _command_skill_parent(command.stem)
        _adapt_skill_dir(dest, user_invoked_only=bool(parent) and _user_invoked_only(
            REPO_ROOT / "cli" / "claude" / "skills" / parent / "SKILL.md"))


def _user_invoked_only(skill_md: Path) -> bool:
    """Claude's `disable-model-invocation: true` (the skill runs only when the
    user asks for it)."""
    text = skill_md.read_text(encoding="utf-8") if skill_md.exists() else ""
    frontmatter = text.split("\n---", 1)[0] if text.startswith("---") else ""
    return bool(re.search(r"^disable-model-invocation:\s*true\s*$", frontmatter, re.MULTILINE))


def _adapt_skill_dir(dest: Path, user_invoked_only: bool = False) -> None:
    """Turn a Claude skill copied into the shared root into a portable one."""
    if user_invoked_only or _user_invoked_only(dest / "SKILL.md"):
        # Codex ignores Claude's frontmatter key; its equivalent is a policy
        # in agents/openai.yaml (Antigravity reads the frontmatter key).
        (dest / "agents").mkdir(exist_ok=True)
        (dest / "agents" / "openai.yaml").write_text(
            "policy:\n  allow_implicit_invocation: false\n", encoding="utf-8")
    _sanitize_skill_frontmatter(dest / "SKILL.md")
    _rewrite_for_shared_root(dest)
    _split_large_skill(dest)
    _mark_skill_dir(dest)


def deploy_shared_outputs(
    project: Path, sel: Selections, adapters: list[CliAdapter],
    dropped: list[CliAdapter], mcp_state: dict,
) -> None:
    """Write every shared output a selected CLI reads, once each, and remove
    the foundry's part of any output that only dropped CLIs read."""
    outputs = set().union(*(a.shared_outputs for a in adapters))
    orphaned = set().union(*(a.shared_outputs for a in dropped)) - outputs
    if outputs & {AGENTS_MD, AGENTS_SKILLS}:
        print("\n  → Shared (AGENTS.md, .agents/ — read by several CLIs)")
    if MCP_JSON in outputs:
        write_mcp_servers(project, sel.mcp_servers, mcp_state)
    elif MCP_JSON in orphaned:
        write_mcp_servers(project, [], mcp_state)
    if AGENTS_MD in outputs:
        limits = {a.display_name: a.agents_md_limit for a in adapters if a.agents_md_limit}
        write_agents_md(project, sel, limits,
                        absorb_claude_md=any(a.id == "claude" for a in adapters))
    elif AGENTS_MD in orphaned:
        remove_agents_md(project, sel.project_name)
    if AGENTS_SKILLS in outputs:
        deploy_shared_skills(project, sel)
    elif AGENTS_SKILLS in orphaned:
        remove_shared_skills(project)
