"""Project files read by more than one CLI, written once per run.

Copilot CLI, Codex and Antigravity all load AGENTS.md and .agents/skills/;
Claude Code and Copilot both read the workspace .mcp.json. Adapters declare
which of these their CLI consumes (``CliAdapter.shared_outputs``) and the
orchestrator calls :func:`deploy_shared_outputs` once for the union, so no
two adapters render the same file.

AGENTS.md size budget: Antigravity reads at most 24,000 bytes per rule file
and Codex stops after 32 KiB of project docs in total, and both truncate
silently. The foundry block is therefore capped at ``AGENTS_MD_BUDGET``:
rules are embedded in priority order while they fit, and the rest go to
``.agents/rules/foundry-<rule>.md`` (with Antigravity trigger frontmatter, so
it loads them natively) and are listed in AGENTS.md as pointers. Each rule
lands in exactly one of the two places, so no CLI reads a rule twice.

Ownership: .agents/ is a cross-vendor directory that other tools write to
too (Codex's Claude importer copies .claude/skills/ into .agents/skills/).
A name alone therefore doesn't prove the foundry wrote something, so every
file or skill directory the foundry writes there carries a marker, and the
prune passes only ever touch marked content.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from .adapters.base import AGENTS_MD, AGENTS_SKILLS, MCP_JSON, Selections
from .deploy import write_mcp_servers
from .instructions import (
    has_agent_foundry_header,
    prepend_agent_foundry_header,
    render_env_commands,
    rule_description,
    update_agent_foundry_header,
)
from .paths import AGENT_FOUNDRY_MARKER_END, AGENT_FOUNDRY_MARKER_START, REPO_ROOT
from .registry import CLAUDE_ONLY_RULES, MODULAR_RULES, PORTABLE_SKILLS

# Leaves room for the project's own AGENTS.md content under both the
# Antigravity (24,000 B/file) and Codex (32 KiB total) limits.
AGENTS_MD_BUDGET = 20_000

AGENTS_RULES_DIR = Path(".agents") / "rules"
AGENTS_SKILLS_DIR = Path(".agents") / "skills"

# Ownership markers (see module docstring). Overflow rules are namespaced
# `foundry-<rule>.md` so they never collide with a project's own rules.
_RULE_PREFIX = "foundry-"
_RULE_MARKER = ("<!-- agent-foundry: managed file, regenerated by setup.py — "
                "edit the foundry source rule instead -->")
_SKILL_MARKER_FILE = ".agent-foundry"

# Embed priority after the base rules: tooling first, templates last.
_MODULAR_PRIORITY = ("lang", "platform", "security", "templates")

# SKILL.md frontmatter keys some reader of .agents/skills/ doesn't accept.
# Copilot CLI has no `model` key (Codex and Antigravity ignore it).
_UNSUPPORTED_SKILL_FRONTMATTER = ("model",)


@dataclass(frozen=True)
class _Rule:
    name: str             # rule filename, e.g. "python.md"
    category: str | None  # modular category, or None for a base rule
    body: str
    dest: str             # overflow path, e.g. ".agents/rules/foundry-python.md"


def portable_rules(sel: Selections) -> list[_Rule]:
    """Selected rules for non-Claude CLIs, in embed-priority order.

    Claude-only rules are dropped. A modular rule whose filename collides
    with an earlier rule overflows to ``foundry-<category>-<rule>``,
    matching the .claude/rules/ collision convention.
    """
    candidates: list[tuple[str, str | None, Path]] = [
        (rule, None, REPO_ROOT / "common" / "rules" / rule) for rule in sel.base
    ]
    extra = [c for c in sel.modular if c not in _MODULAR_PRIORITY]
    for category in (*_MODULAR_PRIORITY, *extra):
        candidates += [
            (rule, category, REPO_ROOT / "common" / "rule-library" / category / rule)
            for rule in sel.modular.get(category, [])
        ]
    rules: list[_Rule] = []
    used: set[str] = set()
    for name, category, src in candidates:
        if name in CLAUDE_ONLY_RULES or not src.is_file():
            continue
        filename = f"{category}-{name}" if name in used else name
        used.add(filename)
        rules.append(_Rule(name, category, src.read_text(encoding="utf-8").strip(),
                           (AGENTS_RULES_DIR / f"{_RULE_PREFIX}{filename}").as_posix()))
    return rules


def _render_block(env: str, embedded: list[_Rule], pointers: list[_Rule]) -> str:
    sections = [AGENT_FOUNDRY_MARKER_START,
                "## Coding Standards (agent-foundry)",
                "",
                "These standards are managed by agent-foundry and apply to any "
                "CLI that reads `AGENTS.md`.",
                "",
                "### Environment",
                "",
                "```bash",
                env,
                "```",
                ""]
    for rule in embedded:
        sections += [f"<!-- rule: {rule.name} -->", rule.body, ""]
    if pointers:
        sections += ["### More rules", "",
                     "Read the matching file before working in its area:", ""]
        sections += [f"- `{rule.dest}` — {rule_description(rule.name)}" for rule in pointers]
        sections.append("")
    sections.append(AGENT_FOUNDRY_MARKER_END)
    return "\n".join(sections)


def render_agents_block(
    sel: Selections, budget: int = AGENTS_MD_BUDGET,
) -> tuple[str, list[_Rule]]:
    """Render the marker-wrapped AGENTS.md block within ``budget`` bytes.

    Returns the block and the rules that overflowed to .agents/rules/.
    Each rule is embedded if the block, with every later rule still counted
    as a pointer, stays within budget — so the final block always fits.
    """
    env = render_env_commands(sel.langs)
    rules = portable_rules(sel)
    embedded: list[_Rule] = []
    overflow: list[_Rule] = []
    for i, rule in enumerate(rules):
        candidate = _render_block(env, [*embedded, rule], [*overflow, *rules[i + 1:]])
        if len(candidate.encode("utf-8")) <= budget:
            embedded.append(rule)
        else:
            overflow.append(rule)
    return _render_block(env, embedded, overflow), overflow


def _rule_frontmatter(rule: _Rule) -> str:
    """Antigravity rule frontmatter: base rules always apply, language rules
    trigger on their file extensions, everything else on model decision."""
    extensions = MODULAR_RULES.get("lang", {}).get(rule.name, {}).get("detect", [])
    if rule.category is None:
        trigger = "trigger: always_on"
    elif rule.category == "lang" and extensions:
        globs = ", ".join(f"**/*{ext}" for ext in extensions)
        trigger = f"trigger: glob\nglobs: {json.dumps(globs)}"
    else:
        trigger = "trigger: model_decision"
    return f"---\n{trigger}\ndescription: {json.dumps(rule_description(rule.name))}\n---\n"


def _write_overflow_rules(project: Path, overflow: list[_Rule]) -> None:
    """Write overflow rules and remove foundry-marked ones no longer needed.
    Unmarked files (the project's own rules) are never touched."""
    rules_dir = project / AGENTS_RULES_DIR
    keep = {Path(r.dest).name for r in overflow}
    if rules_dir.is_dir():
        for existing in sorted(rules_dir.glob(f"{_RULE_PREFIX}*.md")):
            if existing.name in keep:
                continue
            if _RULE_MARKER in existing.read_text(encoding="utf-8"):
                existing.unlink()
                print(f"  Removed stale foundry rule: {AGENTS_RULES_DIR.as_posix()}/{existing.name}")
    if not overflow:
        return
    rules_dir.mkdir(parents=True, exist_ok=True)
    for rule in overflow:
        (project / rule.dest).write_text(
            f"{_rule_frontmatter(rule)}{_RULE_MARKER}\n\n{rule.body}\n", encoding="utf-8")
    print(f"  {len(overflow)} rule(s) over the AGENTS.md budget → "
          f"{AGENTS_RULES_DIR.as_posix()}/: {', '.join(r.name for r in overflow)}")


def write_agents_md(project: Path, sel: Selections) -> None:
    """Create or update the foundry block in AGENTS.md (+ rule overflow)."""
    block, overflow = render_agents_block(sel, AGENTS_MD_BUDGET)
    agents_md = project / "AGENTS.md"
    if not agents_md.exists():
        agents_md.write_text(f"# {sel.project_name}\n\n{block}\n", encoding="utf-8")
        print("  Created AGENTS.md")
    else:
        existing = agents_md.read_text(encoding="utf-8")
        if has_agent_foundry_header(existing):
            agents_md.write_text(update_agent_foundry_header(existing, block),
                                 encoding="utf-8")
            print("  Updated agent-foundry block in AGENTS.md")
        else:
            (project / "AGENTS.md.old").write_text(existing, encoding="utf-8")
            agents_md.write_text(prepend_agent_foundry_header(existing, block),
                                 encoding="utf-8")
            print("  Merged agent-foundry block into AGENTS.md "
                  "(original saved to AGENTS.md.old)")
    _write_overflow_rules(project, overflow)


def _sanitize_skill_frontmatter(skill_md: Path) -> None:
    """Drop SKILL.md frontmatter keys some shared-root reader rejects."""
    if not skill_md.exists():
        return
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return
    end = text.find("\n---", 3)
    if end == -1:
        return
    fm, rest = text[:end], text[end:]
    drop = re.compile(rf"^\s*({'|'.join(_UNSUPPORTED_SKILL_FRONTMATTER)})\s*:.*$\n?",
                      re.MULTILINE)
    skill_md.write_text(drop.sub("", fm) + rest, encoding="utf-8")


def deploy_shared_skills(project: Path, sel: Selections) -> None:
    """Deploy the selected portable skills to .agents/skills/.

    Foundry-marked skill directories that are no longer selected (or no
    longer portable) are removed. An unmarked directory is the project's
    own — even if it shares a foundry skill's name — and is left alone.
    """
    skills_root = project / AGENTS_SKILLS_DIR
    wanted = [s for s in sel.skills if s in PORTABLE_SKILLS]
    if skills_root.is_dir():
        for existing in sorted(skills_root.iterdir()):
            if (existing.name not in wanted and existing.is_dir()
                    and (existing / _SKILL_MARKER_FILE).is_file()):
                shutil.rmtree(existing)
                print(f"  Removed stale foundry skill: "
                      f"{AGENTS_SKILLS_DIR.as_posix()}/{existing.name}/")
    for name in wanted:
        src = REPO_ROOT / "cli" / "claude" / "skills" / name
        if not src.is_dir():
            continue
        dest = skills_root / name
        if dest.exists():
            if not (dest / _SKILL_MARKER_FILE).is_file():
                print(f"  Left project-owned {AGENTS_SKILLS_DIR.as_posix()}/{name}/ "
                      "in place (foundry copy not deployed)")
                continue
            shutil.rmtree(dest)
        shutil.copytree(src, dest)
        _sanitize_skill_frontmatter(dest / "SKILL.md")
        (dest / _SKILL_MARKER_FILE).write_text(
            "Managed by agent-foundry; regenerated by setup.py.\n", encoding="utf-8")
        print(f"  Deployed skill → {AGENTS_SKILLS_DIR.as_posix()}/{name}/")


def deploy_shared_outputs(project: Path, sel: Selections, outputs: set[str]) -> None:
    """Write every shared output some selected CLI consumes, once each."""
    if outputs & {AGENTS_MD, AGENTS_SKILLS}:
        print("\n  → Shared (AGENTS.md, .agents/ — read by several CLIs)")
    if MCP_JSON in outputs and sel.mcp_servers:
        write_mcp_servers(project, sel.mcp_servers)
    if AGENTS_MD in outputs:
        write_agents_md(project, sel)
    if AGENTS_SKILLS in outputs:
        deploy_shared_skills(project, sel)
