"""Google Antigravity CLI (agy) adapter (verified against agy 1.2.10).

Shared outputs (written once by the orchestrator, see foundry/shared.py):
- coding-standard rules → AGENTS.md (Antigravity reads 24,000 bytes of a
  rule file, then truncates); overflow rules in .agents/rules/ load natively
  through their trigger frontmatter
- portable skills and portable Claude commands → .agents/skills/

Antigravity-native, under .agents/:
- subagents → .agents/agents/<name>.md
- MCP servers → .agents/mcp_config.json
- formatter hooks → the "agent-foundry" entry of .agents/hooks.json, running
  scripts from .agents/agent-foundry/hooks/

Antigravity loads a workspace's .agents/ customizations only once the
folder is trusted.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from ..convert import WRITE_TOOLS, agent_tools, rewrite, split_frontmatter
from ..deploy import install_hook_scripts, selected_mcp_servers
from ..paths import AGENTS_DIR
from .base import AGENTS_MD, AGENTS_SKILLS, CliAdapter, DeployContext, DeployResult, Selections

_AGENTS_DIR = Path(".agents") / "agents"
_MCP_CONFIG = Path(".agents") / "mcp_config.json"
_HOOKS_JSON = Path(".agents") / "hooks.json"
# Hook commands run from the directory holding hooks.json (.agents/).
_HOOK_SCRIPTS_DIR = Path(".agents") / "agent-foundry" / "hooks"
_HOOK_NAME = "agent-foundry"
# Tool names are the lowercased step types; these are the file-editing ones.
_HOOK_MATCHER = "write_to_file|replace_file_content|multi_replace_file_content"

# Ownership marker: a YAML comment opening every agent file's frontmatter.
_MANAGED_COMMENT = "# Managed by agent-foundry; regenerated by setup.py — edit the foundry source instead."

# Read-only Claude tools → Antigravity tool names. Agents with write tools
# inherit Antigravity's default toolset instead of an explicit list.
_READ_TOOLS = {"Read": ["view_file"], "Grep": ["grep_search"],
               "Glob": ["find_by_name", "list_dir"], "Bash": ["run_command"]}

_REWRITES = (("Claude Code", "Antigravity"), ("CLAUDE.md", "AGENTS.md"))


# ── Subagents ──


def _demote_h1(body: str) -> str:
    """Antigravity splits an agent's prompt on H1 headings, so the body's
    own H1s become H2s under a single `# System Prompt`. Lines inside code
    fences (e.g. `# comment` in bash) are left alone."""
    lines, in_fence = [], False
    for line in body.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
        elif not in_fence and line.startswith("# "):
            line = "#" + line
        lines.append(line)
    return "\n".join(lines)


def render_agent_md(src: Path) -> str | None:
    """Antigravity agent file for a Claude agent, or None if it lacks a
    name, description or body. ``model`` is dropped (Antigravity agents
    inherit the parent's model)."""
    meta, body = split_frontmatter(src.read_text(encoding="utf-8"))
    name, description, body = meta.get("name"), meta.get("description"), body.strip()
    if not (name and description and body):
        return None
    frontmatter = ["---", _MANAGED_COMMENT,
                   f"name: {json.dumps(name)}",
                   f"description: {json.dumps(rewrite(description, _REWRITES))}"]
    tools = agent_tools(meta)
    if tools and not tools & WRITE_TOOLS:
        agy_tools = sorted({t for tool in tools for t in _READ_TOOLS.get(tool, [])})
        frontmatter.append(f"tools: [{', '.join(agy_tools)}]")
    frontmatter.append("---")
    return ("\n".join(frontmatter) + "\n# System Prompt\n\n"
            + _demote_h1(rewrite(body, _REWRITES)) + "\n")


def _is_managed(path: Path) -> bool:
    return _MANAGED_COMMENT in path.read_text(encoding="utf-8").split("\n---", 1)[0]


def _deploy_agents(project: Path, agents: list[str]) -> int:
    """Write selected agents; prune foundry agents no longer selected."""
    agents_dir = project / _AGENTS_DIR
    keep: set[str] = set()
    for agent in agents:
        src = AGENTS_DIR / agent
        rendered = render_agent_md(src) if src.is_file() else None
        if rendered is None:
            continue
        dest = agents_dir / src.name
        keep.add(dest.name)
        if dest.exists() and not _is_managed(dest):
            print(f"  Left project-owned {_AGENTS_DIR.as_posix()}/{dest.name} in place")
            continue
        agents_dir.mkdir(parents=True, exist_ok=True)
        dest.write_text(rendered, encoding="utf-8")
    if agents_dir.is_dir():
        for existing in sorted(agents_dir.glob("*.md")):
            if existing.name not in keep and _is_managed(existing):
                existing.unlink()
                print(f"  Removed stale foundry agent: {_AGENTS_DIR.as_posix()}/{existing.name}")
    if keep:
        print(f"  Deployed {len(keep)} agent(s) → {_AGENTS_DIR.as_posix()}/")
    return len(keep)


# ── MCP servers (.agents/mcp_config.json) ──


def _agy_server(entry: dict) -> dict:
    """Map a cross-vendor .mcp.json entry to Antigravity's schema: stdio keys
    carry over; remote servers use `serverUrl` (not `url`/`type`)."""
    server = {k: entry[k] for k in ("command", "args", "env", "headers") if k in entry}
    if "url" in entry:
        server["serverUrl"] = entry["url"]
    return server


def _load_json(path: Path) -> dict | None:
    """The file's JSON object ({} if missing), or None if it isn't one."""
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as err:
        print(f"  ⚠ {path.name} doesn't parse as plain JSON ({err}) — left unchanged")
        return None
    if not isinstance(data, dict):
        print(f"  ⚠ {path.name} isn't a JSON object — left unchanged")
        return None
    return data


def _write_json_or_remove(path: Path, data: dict) -> None:
    if data:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    elif path.exists():
        path.unlink()  # the file held nothing but foundry entries


def _deploy_mcp(project: Path, servers: list[str]) -> int:
    """Reconcile foundry servers in .agents/mcp_config.json.

    JSON has no comments to mark ownership, so an entry counts as the
    foundry's only while it still equals the catalog rendering: an entry the
    project added or edited (say, with a real API key) is never overwritten
    or removed. Returns servers present from the selection.
    """
    path = project / _MCP_CONFIG
    data = _load_json(path)
    if data is None:
        return 0
    current = data.setdefault("mcpServers", {})
    catalog = {name: _agy_server(entry) for name, entry in selected_mcp_servers(None).items()}
    deployed = 0
    for name, rendered in catalog.items():
        existing = current.get(name)
        if name in servers:
            if existing is None:
                current[name] = rendered
            elif existing != rendered:
                print(f"  Kept the project's own mcpServers.{name} in {_MCP_CONFIG.as_posix()}")
            deployed += 1
        elif existing == rendered:
            del current[name]
    if not current:
        data.pop("mcpServers")
    _write_json_or_remove(path, data)
    return deployed


# ── Hooks (.agents/hooks.json) ──


def _deploy_hooks(project: Path, hooks: list[str]) -> int:
    """Reconcile the foundry's named hook in .agents/hooks.json (other named
    hooks are the project's) and the scripts it runs. Returns hooks deployed."""
    path = project / _HOOKS_JSON
    data = _load_json(path)
    if data is None:
        return 0
    data.pop(_HOOK_NAME, None)
    scripts_rel = _HOOK_SCRIPTS_DIR.relative_to(".agents").as_posix()
    if hooks:
        # PostToolUse hooks must answer with a JSON object on stdout.
        data[_HOOK_NAME] = {"PostToolUse": [{"matcher": _HOOK_MATCHER, "hooks": [
            {"type": "command", "command": f"{scripts_rel}/{script}; echo '{{}}'", "timeout": 120}
            for script in hooks]}]}
    _write_json_or_remove(path, data)

    scripts_dir = project / _HOOK_SCRIPTS_DIR  # foundry-owned namespace
    if scripts_dir.is_dir():
        shutil.rmtree(scripts_dir)
    install_hook_scripts(scripts_dir, hooks)
    if scripts_dir.parent.is_dir() and not any(scripts_dir.parent.iterdir()):
        scripts_dir.parent.rmdir()
    if hooks:
        print(f"  Deployed {len(hooks)} hook(s) → {_HOOKS_JSON.as_posix()}")
    return len(hooks)


# ── Trust ──


def workspace_trusted(project: Path) -> bool:
    """Whether Antigravity's settings list ``project`` (or a parent) as trusted."""
    settings = Path.home() / ".gemini" / "antigravity-cli" / "settings.json"
    try:
        trusted = json.loads(settings.read_text(encoding="utf-8")).get("trustedWorkspaces", [])
    except (OSError, json.JSONDecodeError, AttributeError):
        return False
    return any(project == Path(t) or Path(t) in project.parents for t in trusted)


class AntigravityAdapter(CliAdapter):
    id = "agy"
    display_name = "Google Antigravity CLI"
    shared_outputs = frozenset({AGENTS_MD, AGENTS_SKILLS})
    agents_md_limit = 24_000  # bytes per rule file

    def config_root(self, project: Path) -> Path:
        return project / ".agents"

    def supported_artifacts(self) -> set[str]:
        return {"rules", "skills", "commands", "agents", "hooks", "mcp"}

    def deploy(self, project: Path, sel: Selections, ctx: DeployContext) -> DeployResult:
        _deploy_agents(project, sel.agents)
        servers = _deploy_mcp(project, sel.mcp_servers)
        _deploy_hooks(project, sel.hooks)
        if servers:
            print(f"  Deployed {servers} MCP server(s) → {_MCP_CONFIG.as_posix()}")
        if not workspace_trusted(project):
            print("  Antigravity loads .agents/ (skills, rules, agents, MCP servers, hooks)")
            print("  only in trusted workspaces: run `agy` here once and trust the folder.")
        return DeployResult(ok=True)
