"""OpenAI Codex CLI adapter (verified against Codex 0.156.1).

Shared outputs (written once by the orchestrator, see foundry/shared.py):
- coding-standard rules → AGENTS.md (Codex reads 32 KiB of project docs,
  then truncates silently)
- portable skills and portable Claude commands → .agents/skills/

Codex-native, under .codex/:
- subagents → .codex/agents/<name>.toml (name, description,
  developer_instructions; the same mapping as Codex's own Claude importer)
- MCP servers → a marker-delimited [mcp_servers.*] block in .codex/config.toml
- formatter hooks → .codex/hooks.json + scripts in .codex/hooks/agent-foundry/

Codex loads .codex/ only in trusted projects, and runs each non-managed hook
only after the user approves it in /hooks — so deployed hooks stay inert
until approved. AGENTS.md and .agents/skills/ load either way.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import tomllib
from pathlib import Path

from ..deploy import install_hook_scripts, selected_mcp_servers
from ..paths import AGENTS_DIR
from ..registry import HOOK_SCRIPTS
from .base import AGENTS_MD, AGENTS_SKILLS, CliAdapter, DeployContext, DeployResult, Selections

_AGENTS_DIR = Path(".codex") / "agents"
_CONFIG = Path(".codex") / "config.toml"
_HOOKS_JSON = Path(".codex") / "hooks.json"
_HOOKS_DIR = Path(".codex") / "hooks" / "agent-foundry"

# Ownership markers: the first line of every agent file the foundry writes,
# and the delimiters of its block in config.toml. Unmarked content is the
# project's own and is never overwritten or pruned.
_MANAGED_HEADER = "# Managed by agent-foundry; regenerated by setup.py — edit the foundry source instead."
_BLOCK_START = "# >>> agent-foundry: managed block, regenerated by setup.py >>>"
_BLOCK_END = "# <<< agent-foundry <<<"

# Codex hook matchers see apply_patch under its Claude aliases too; naming
# all three keeps the intent explicit.
_HOOK_MATCHER = "apply_patch|Edit|Write"

# Claude Code wording in agent bodies, rewritten for Codex (skills are
# invoked as $name there, not /name).
_REWRITES = (("Claude Code", "Codex"), ("CLAUDE.md", "AGENTS.md"),
             ("/update-codemaps", "$update-codemaps"))

# An agent whose Claude tools include none of these can't modify files, so
# it runs in Codex's read-only sandbox.
_WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}


# ── TOML rendering (the standard library only reads TOML) ──


def _toml_str(value: str) -> str:
    """A TOML basic string. JSON string escapes are valid TOML; DEL isn't
    escaped by json but must be in TOML."""
    return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")


def _toml_multiline(value: str) -> str:
    """A readable multi-line literal string, or a basic string when the
    value can't be represented literally."""
    unsafe = "'''" in value or any(
        (ord(c) < 0x20 and c not in "\t\n") or c == "\x7f" for c in value)
    return _toml_str(value) if unsafe else f"'''\n{value}\n'''"


def _toml_key(key: str) -> str:
    return key if re.fullmatch(r"[A-Za-z0-9_-]+", key) else _toml_str(key)


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, str):
        return _toml_str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{_toml_key(k)} = {_toml_value(v)}"
                                for k, v in value.items()) + " }"
    raise TypeError(f"can't render {type(value).__name__} as TOML")


# ── Subagents ──


def _split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Scalar ``key: value`` frontmatter (all foundry agents use) and body."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        key, sep, value = line.partition(":")
        if sep and key.strip():
            meta[key.strip()] = value.strip().strip("\"'")
    return meta, text[end + 4:].lstrip("\n")


def _rewrite(text: str) -> str:
    for old, new in _REWRITES:
        text = text.replace(old, new)
    return text


def render_agent_toml(src: Path) -> str | None:
    """Codex agent role file for a Claude agent, or None if it lacks a
    name, description or body. ``model`` is dropped (Claude model names mean
    nothing to Codex); agents without write tools get a read-only sandbox."""
    meta, body = _split_frontmatter(src.read_text(encoding="utf-8"))
    name, description, body = meta.get("name"), meta.get("description"), body.strip()
    if not (name and description and body):
        return None
    tools = {t.strip() for t in meta.get("tools", "").split(",") if t.strip()}
    lines = [_MANAGED_HEADER,
             f"name = {_toml_str(name)}",
             f"description = {_toml_str(_rewrite(description))}"]
    if tools and not tools & _WRITE_TOOLS:
        lines.append('sandbox_mode = "read-only"')
    lines.append(f"developer_instructions = {_toml_multiline(_rewrite(body))}")
    return "\n".join(lines) + "\n"


def _is_managed(path: Path) -> bool:
    return path.read_text(encoding="utf-8").startswith(_MANAGED_HEADER)


def _deploy_agents(project: Path, agents: list[str]) -> int:
    """Write selected agents; prune foundry agents no longer selected."""
    agents_dir = project / _AGENTS_DIR
    keep: set[str] = set()
    for agent in agents:
        src = AGENTS_DIR / agent
        rendered = render_agent_toml(src) if src.is_file() else None
        if rendered is None:
            continue
        dest = agents_dir / f"{src.stem}.toml"
        keep.add(dest.name)
        if dest.exists() and not _is_managed(dest):
            print(f"  Left project-owned {_AGENTS_DIR.as_posix()}/{dest.name} in place")
            continue
        agents_dir.mkdir(parents=True, exist_ok=True)
        dest.write_text(rendered, encoding="utf-8")
    if agents_dir.is_dir():
        for existing in sorted(agents_dir.glob("*.toml")):
            if existing.name not in keep and _is_managed(existing):
                existing.unlink()
                print(f"  Removed stale foundry agent: {_AGENTS_DIR.as_posix()}/{existing.name}")
    if keep:
        print(f"  Deployed {len(keep)} agent(s) → {_AGENTS_DIR.as_posix()}/")
    return len(keep)


# ── MCP servers (.codex/config.toml) ──


def _codex_server(entry: dict) -> dict:
    """Map a cross-vendor .mcp.json entry to Codex's mcp_servers schema:
    stdio keys carry over; HTTP servers need only `url` (no `type`)."""
    server = {k: entry[k] for k in ("command", "args", "env", "cwd", "url") if k in entry}
    if "headers" in entry:
        server["http_headers"] = entry["headers"]
    return server


def render_mcp_block(servers: dict[str, dict]) -> str:
    lines = [_BLOCK_START]
    for name, entry in servers.items():
        lines.append(f"[mcp_servers.{_toml_key(name)}]")
        lines += [f"{_toml_key(k)} = {_toml_value(v)}" for k, v in _codex_server(entry).items()]
        lines.append("")
    lines.append(_BLOCK_END)
    return "\n".join(lines) + "\n"


def _strip_block(text: str) -> str:
    """``text`` without the foundry block (and the blank lines around it)."""
    start = text.find(_BLOCK_START)
    end = text.find(_BLOCK_END, start)
    if start == -1 or end == -1:
        return text
    parts = [text[:start].rstrip("\n"), text[end + len(_BLOCK_END):].strip("\n")]
    joined = "\n\n".join(p for p in parts if p)
    return f"{joined}\n" if joined else ""


def _deploy_mcp(project: Path, servers: list[str]) -> int:
    """Rewrite the foundry block in .codex/config.toml; the rest of the file
    is the project's and is kept as-is. Returns servers written."""
    path = project / _CONFIG
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    user_text = _strip_block(existing)
    try:
        user_config = tomllib.loads(user_text)
    except tomllib.TOMLDecodeError as err:
        print(f"  ⚠ {_CONFIG.as_posix()} doesn't parse ({err}) — MCP servers not written")
        return 0
    project_defined = set(user_config.get("mcp_servers", {}))
    catalog = selected_mcp_servers(servers)
    for name in sorted(project_defined & set(catalog)):
        print(f"  Left project-defined mcp_servers.{name} in {_CONFIG.as_posix()} in place")
    ours = {k: v for k, v in catalog.items() if k not in project_defined}
    new_text = user_text
    if ours:
        prefix = f"{user_text.rstrip()}\n\n" if user_text.strip() else ""
        new_text = prefix + render_mcp_block(ours)
    if new_text == existing:
        return len(ours)
    if new_text.strip():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_text, encoding="utf-8")
    elif path.exists():
        path.unlink()  # the file held nothing but the foundry block
    return len(ours)


# ── Hooks (.codex/hooks.json) ──


def _hook_command(script: str) -> str:
    """Codex runs hooks from the session cwd, which may be a subdirectory —
    resolve the script from the repository root."""
    return (f'"$(git rev-parse --show-toplevel 2>/dev/null || pwd)'
            f'/{(_HOOKS_DIR / script).as_posix()}"')


def _is_foundry_group(group) -> bool:
    handlers = group.get("hooks", []) if isinstance(group, dict) else []
    return bool(handlers) and all(
        _HOOKS_DIR.as_posix() in str(h.get("command", "")) for h in handlers
        if isinstance(h, dict))


def _deploy_hooks(project: Path, hooks: list[str]) -> int:
    """Reconcile the foundry's PostToolUse group in .codex/hooks.json and
    the scripts it runs; other hook groups are the project's. Returns hooks
    deployed."""
    path = project / _HOOKS_JSON
    data: dict = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as err:
            print(f"  ⚠ {_HOOKS_JSON.as_posix()} doesn't parse ({err}) — hooks not written")
            return 0
    events = data.setdefault("hooks", {}) if isinstance(data, dict) else None
    if not isinstance(events, dict) or not isinstance(events.get("PostToolUse", []), list):
        print(f"  ⚠ {_HOOKS_JSON.as_posix()} has an unexpected shape — hooks not written")
        return 0
    groups = [g for g in events.get("PostToolUse", []) if not _is_foundry_group(g)]
    if hooks:
        groups.append({"matcher": _HOOK_MATCHER, "hooks": [
            {"type": "command", "command": _hook_command(script),
             "statusMessage": f"agent-foundry: {HOOK_SCRIPTS[script]['desc']}"}
            for script in hooks]})
    if groups:
        events["PostToolUse"] = groups
    else:
        events.pop("PostToolUse", None)
    if not events:
        data.pop("hooks")
    if data:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    elif path.exists():
        path.unlink()  # the file held nothing but the foundry group

    scripts_dir = project / _HOOKS_DIR  # foundry-owned namespace
    if scripts_dir.is_dir():
        shutil.rmtree(scripts_dir)
    install_hook_scripts(scripts_dir, hooks)
    if hooks:
        print(f"  Deployed {len(hooks)} hook(s) → {_HOOKS_JSON.as_posix()}")
    return len(hooks)


# ── Trust ──


def project_trusted(project: Path) -> bool:
    """Whether the user's Codex config marks ``project`` as trusted."""
    home = Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex")
    try:
        config = tomllib.loads((home / "config.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return False
    return config.get("projects", {}).get(str(project), {}).get("trust_level") == "trusted"


def _print_trust_hint(project: Path) -> None:
    print("  Codex reads .codex/ (agents, MCP servers, hooks) only in trusted projects.")
    print("  Trust this one by starting `codex` here and accepting the prompt, or add")
    print("  to ~/.codex/config.toml:")
    print(f"      [projects.{_toml_str(str(project))}]")
    print('      trust_level = "trusted"')


class CodexAdapter(CliAdapter):
    id = "codex"
    display_name = "OpenAI Codex CLI"
    shared_outputs = frozenset({AGENTS_MD, AGENTS_SKILLS})
    agents_md_limit = 32 * 1024  # project_doc_max_bytes default

    def config_root(self, project: Path) -> Path:
        return project / ".codex"

    def supported_artifacts(self) -> set[str]:
        return {"rules", "skills", "commands", "agents", "hooks", "mcp"}

    def deploy(self, project: Path, sel: Selections, ctx: DeployContext) -> DeployResult:
        agents = _deploy_agents(project, sel.agents)
        servers = _deploy_mcp(project, sel.mcp_servers)
        hooks = _deploy_hooks(project, sel.hooks)
        if servers:
            print(f"  Deployed {servers} MCP server(s) → {_CONFIG.as_posix()}")
        if (agents or servers or hooks) and not project_trusted(project):
            _print_trust_hint(project)
        if hooks:
            print("  Approve the foundry hooks once in Codex with /hooks "
                  "(Codex skips hooks until approved).")
        return DeployResult(ok=True)
