"""OpenAI Codex CLI adapter (verified against Codex 0.156.1).

Shared outputs (written once by the orchestrator, see foundry/shared.py):
- coding-standard rules → AGENTS.md (Codex reads 32 KiB of project docs,
  then truncates silently)
- portable skills and portable Claude commands → .agents/skills/

Codex-native, under .codex/:
- subagents → .codex/agents/<name>.toml (name, description,
  developer_instructions; the same mapping as Codex's own Claude importer)
- MCP servers → a marker-delimited [mcp_servers.*] block in .codex/config.toml
- formatter hooks → .codex/hooks.json + scripts in .codex/hooks/agent-foundry/

Codex loads .codex/ only in trusted projects, and runs each non-managed hook
only after the user approves it in /hooks — so deployed hooks stay inert
until approved. AGENTS.md and .agents/skills/ load either way.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import tomllib
from pathlib import Path

from ..convert import WRITE_TOOLS, agent_tools, rewrite, split_frontmatter
from ..deploy import (
    _has_filled_placeholder,
    _owned_agent_names,
    install_hook_scripts,
    keep_filled_placeholders,
    selected_mcp_servers,
)
from ..paths import AGENTS_DIR
from ..registry import HOOK_SCRIPTS
from .base import AGENTS_MD, AGENTS_SKILLS, CliAdapter, DeployContext, DeployResult, Selections

_AGENTS_DIR = Path(".codex") / "agents"
_CONFIG = Path(".codex") / "config.toml"
_HOOKS_JSON = Path(".codex") / "hooks.json"
_HOOKS_DIR = Path(".codex") / "hooks" / "agent-foundry"

# Ownership markers: the first line of every agent file the foundry writes,
# and the delimiters of its block in config.toml. Unmarked content is the
# project's own and is never overwritten or pruned.
_MANAGED_HEADER = "# Managed by agent-foundry; regenerated by setup.py — edit the foundry source instead."
_BLOCK_START = "# >>> agent-foundry: managed block, regenerated by setup.py >>>"
_BLOCK_END = "# <<< agent-foundry <<<"

# Codex hook matchers see apply_patch under its Claude aliases too; naming
# all three keeps the intent explicit.
_HOOK_MATCHER = "apply_patch|Edit|Write"

# Claude Code wording in agent bodies, rewritten for Codex (skills are
# invoked as $name there, not /name).
_REWRITES = (("Claude Code", "Codex"), ("CLAUDE.md", "AGENTS.md"),
             ("/update-codemaps", "$update-codemaps"))

# ── TOML rendering (the standard library only reads TOML) ──


def _toml_str(value: str) -> str:
    """A TOML basic string. JSON string escapes are valid TOML; DEL isn't
    escaped by json but must be in TOML."""
    return json.dumps(value, ensure_ascii=False).replace("\x7f", "\\u007f")


def _toml_multiline(value: str) -> str:
    """A readable multi-line literal string, or a basic string when the
    value can't be represented literally."""
    unsafe = "'''" in value or any(
        (ord(c) < 0x20 and c not in "\t\n") or c == "\x7f" for c in value)
    return _toml_str(value) if unsafe else f"'''\n{value}\n'''"


def _toml_key(key: str) -> str:
    return key if re.fullmatch(r"[A-Za-z0-9_-]+", key) else _toml_str(key)


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, str):
        return _toml_str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{_toml_key(k)} = {_toml_value(v)}"
                                for k, v in value.items()) + " }"
    raise TypeError(f"can't render {type(value).__name__} as TOML")


# ── Subagents ──


def render_agent_toml(src: Path) -> str | None:
    """Codex agent role file for a Claude agent, or None if it lacks a
    name, description or body. ``model`` is dropped (Claude model names mean
    nothing to Codex); agents without write tools get a read-only sandbox."""
    meta, body = split_frontmatter(src.read_text(encoding="utf-8"))
    name, description, body = meta.get("name"), meta.get("description"), body.strip()
    if not (name and description and body):
        return None
    tools = agent_tools(meta)
    lines = [_MANAGED_HEADER,
             f"name = {_toml_str(name)}",
             f"description = {_toml_str(rewrite(description, _REWRITES))}"]
    if tools and not tools & WRITE_TOOLS:
        lines.append('sandbox_mode = "read-only"')
    lines.append(f"developer_instructions = {_toml_multiline(rewrite(body, _REWRITES))}")
    return "\n".join(lines) + "\n"


def _is_managed(path: Path) -> bool:
    return path.read_text(encoding="utf-8", errors="replace").startswith(_MANAGED_HEADER)


def _deploy_agents(project: Path, agents: list[str]) -> int:
    """Write selected agents; prune foundry agents no longer selected."""
    agents_dir = project / _AGENTS_DIR
    keep: set[str] = set()
    for agent in agents:
        src = AGENTS_DIR / agent
        rendered = render_agent_toml(src) if src.is_file() else None
        if rendered is None:
            continue
        dest = agents_dir / f"{src.stem}.toml"
        keep.add(dest.name)
        if dest.exists() and not _is_managed(dest):
            print(f"  Left project-owned {_AGENTS_DIR.as_posix()}/{dest.name} in place")
            continue
        agents_dir.mkdir(parents=True, exist_ok=True)
        dest.write_text(rendered, encoding="utf-8")
    if agents_dir.is_dir():
        owned = {Path(a).stem for a in _owned_agent_names()}  # plus the marker, below
        for existing in sorted(agents_dir.glob("*.toml")):
            if existing.name not in keep and existing.stem in owned and _is_managed(existing):
                existing.unlink()
                print(f"  Removed stale foundry agent: {_AGENTS_DIR.as_posix()}/{existing.name}")
    if agents_dir.is_dir() and not any(agents_dir.iterdir()):
        agents_dir.rmdir()
    if keep:
        print(f"  Deployed {len(keep)} agent(s) → {_AGENTS_DIR.as_posix()}/")
    return len(keep)


# ── MCP servers (.codex/config.toml) ──


def _codex_server(entry: dict) -> dict:
    """Map a cross-vendor .mcp.json entry to Codex's mcp_servers schema:
    stdio keys carry over; HTTP servers need only `url` (no `type`)."""
    server = {k: entry[k] for k in ("command", "args", "env", "cwd", "url") if k in entry}
    if "headers" in entry:
        server["http_headers"] = entry["headers"]
    return server


def render_mcp_block(servers: dict[str, dict]) -> str:
    """The managed block for ``servers`` (already in Codex's schema)."""
    lines = [_BLOCK_START]
    for name, server in servers.items():
        lines.append(f"[mcp_servers.{_toml_key(name)}]")
        lines += [f"{_toml_key(k)} = {_toml_value(v)}" for k, v in server.items()]
        lines.append("")
    lines.append(_BLOCK_END)
    return "\n".join(lines) + "\n"


def _block_servers(text: str) -> dict:
    """The mcp_servers currently inside the foundry block of ``text``."""
    start = text.find(_BLOCK_START)
    end = text.find(_BLOCK_END, start)
    if start == -1 or end == -1:
        return {}
    return tomllib.loads(text[start:end]).get("mcp_servers", {})


def _strip_block(text: str) -> str:
    """``text`` without the foundry block (and the blank lines around it)."""
    start = text.find(_BLOCK_START)
    end = text.find(_BLOCK_END, start)
    if start == -1 or end == -1:
        return text
    parts = [text[:start].rstrip("\n"), text[end + len(_BLOCK_END):].strip("\n")]
    joined = "\n\n".join(p for p in parts if p)
    return f"{joined}\n" if joined else ""


def _deploy_mcp(project: Path, servers: list[str]) -> int:
    """Rewrite the foundry block in .codex/config.toml; the rest of the file
    is the project's and is kept as-is. Returns servers written."""
    path = project / _CONFIG
    try:
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        user_text = _strip_block(existing)
        user_config = tomllib.loads(user_text)
        previous = _block_servers(existing)
    except (tomllib.TOMLDecodeError, UnicodeDecodeError) as err:
        print(f"  ⚠ {_CONFIG.as_posix()} doesn't parse ({err}) — MCP servers not written")
        return 0
    user_servers = user_config.get("mcp_servers", {})
    if not isinstance(user_servers, dict):
        print(f"  ⚠ {_CONFIG.as_posix()} defines mcp_servers as a non-table — MCP servers not written")
        return 0
    catalog = selected_mcp_servers(servers)
    for name in sorted(set(user_servers) & set(catalog)):
        print(f"  Left project-defined mcp_servers.{name} in {_CONFIG.as_posix()} in place")
    # A real API key typed into the managed block survives regeneration...
    ours = {k: keep_filled_placeholders(_codex_server(v), previous.get(k))
            for k, v in catalog.items() if k not in user_servers}
    # ...and deselecting that server moves it out of the block, so the key
    # is kept as the project's own config instead of being dropped.
    full_catalog = selected_mcp_servers(None)
    for name, entry in previous.items():
        if (name not in ours and name in full_catalog and name not in user_servers
                and _has_filled_placeholder(_codex_server(full_catalog[name]), entry)):
            user_text = (f"{user_text.rstrip()}\n\n" if user_text.strip() else "") + \
                render_mcp_block({name: entry}).replace(_BLOCK_START + "\n", "").replace(
                    _BLOCK_END + "\n", "")
            print(f"  Kept deselected MCP server {name} (it holds a value you filled in) — "
                  f"moved it out of the foundry block in {_CONFIG.as_posix()}")
    new_text = user_text
    if ours:
        prefix = f"{user_text.rstrip()}\n\n" if user_text.strip() else ""
        new_text = prefix + render_mcp_block(ours)
    if new_text == existing:
        return len(ours)
    try:
        tomllib.loads(new_text)
    except tomllib.TOMLDecodeError as err:  # e.g. servers also set as dotted/inline keys
        print(f"  ⚠ merging MCP servers into {_CONFIG.as_posix()} would make it invalid "
              f"({err}) — left unchanged")
        return 0
    if new_text.strip():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_text, encoding="utf-8")
    elif path.exists():
        path.unlink()  # the file held nothing but the foundry block
    return len(ours)


# ── Hooks (.codex/hooks.json) ──


def _hook_script_finder(script: str) -> str:
    """POSIX sh program that runs ``script`` from the project's
    .codex/hooks/agent-foundry/. Codex runs hooks from the session cwd,
    which may sit below the project (or the project below the git root),
    so walk up to the nearest directory with .codex/hooks.json — and stop
    there: a same-named script further up is outside the project. Exits 0
    quietly if the script isn't there.

    Written with if/then only — no &, |, <, > — so `cmd /C` on Windows
    passes it to bash intact (``commandWindows``)."""
    rel = (_HOOKS_DIR / script).as_posix()
    return (f's={rel}; d=$PWD; while true; do '
            'if [ -f "$d/.codex/hooks.json" ]; then '
            'if [ -f "$d/$s" ]; then exec bash "$d/$s"; fi; exit 0; fi; '
            'if [ "$d" = / ]; then exit 0; fi; d=$(dirname "$d"); done')


def _hook_handler(script: str) -> dict:
    """Codex runs `command` via `$SHELL -lc` (so wrap in `sh -c` to be
    independent of the user's shell, e.g. fish) and `commandWindows` via
    `cmd /C` (Git Bash's `bash` must be on PATH)."""
    finder = _hook_script_finder(script)
    return {"type": "command", "command": f"sh -c '{finder}'",
            "commandWindows": f"bash -c '{finder}'",
            "statusMessage": f"agent-foundry: {HOOK_SCRIPTS[script]['desc']}"}


def _is_foundry_handler(handler) -> bool:
    return isinstance(handler, dict) and _HOOKS_DIR.as_posix() in str(handler.get("command", ""))


def _deploy_hooks(project: Path, hooks: list[str]) -> int:
    """Reconcile the foundry's PostToolUse group in .codex/hooks.json and
    the scripts it runs; other hook groups are the project's. Returns hooks
    deployed."""
    path = project / _HOOKS_JSON
    data: dict = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError) as err:
            print(f"  ⚠ {_HOOKS_JSON.as_posix()} doesn't parse ({err}) — hooks not written")
            return 0
    original = json.loads(json.dumps(data))
    events = data.setdefault("hooks", {}) if isinstance(data, dict) else None
    if not isinstance(events, dict) or not isinstance(events.get("PostToolUse", []), list):
        print(f"  ⚠ {_HOOKS_JSON.as_posix()} has an unexpected shape — hooks not written")
        return 0
    # Reconcile per handler: drop the foundry's handlers wherever they are
    # (a user may have added their own handler to the foundry's group), keep
    # everything else, then add the current foundry group.
    groups = []
    for group in events.get("PostToolUse", []):
        if isinstance(group, dict) and isinstance(group.get("hooks"), list):
            kept = [h for h in group["hooks"] if not _is_foundry_handler(h)]
            if not kept:
                continue
            group = {**group, "hooks": kept}
        groups.append(group)
    if hooks:
        groups.append({"matcher": _HOOK_MATCHER,
                       "hooks": [_hook_handler(script) for script in hooks]})
    if groups:
        events["PostToolUse"] = groups
    else:
        events.pop("PostToolUse", None)
    if not events and "hooks" not in original:
        data.pop("hooks")
    if data != original:
        if data.get("hooks") or set(data) - {"hooks"}:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        elif path.exists():
            path.unlink()  # the file held nothing but the foundry group

    scripts_dir = project / _HOOKS_DIR  # foundry-owned namespace
    if scripts_dir.is_dir():
        shutil.rmtree(scripts_dir)
    install_hook_scripts(scripts_dir, hooks)
    for empty in (scripts_dir.parent, scripts_dir.parent.parent):  # .codex/hooks, .codex
        if empty.is_dir() and not any(empty.iterdir()):
            empty.rmdir()
    if hooks:
        print(f"  Deployed {len(hooks)} hook(s) → {_HOOKS_JSON.as_posix()}")
    return len(hooks)


# ── Trust ──


def project_trusted(project: Path) -> bool:
    """Whether the user's Codex config marks ``project`` as trusted."""
    home = Path(os.environ.get("CODEX_HOME") or Path.home() / ".codex")
    try:
        config = tomllib.loads((home / "config.toml").read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return False
    return config.get("projects", {}).get(str(project), {}).get("trust_level") == "trusted"


def _print_trust_hint(project: Path) -> None:
    print("  Codex reads .codex/ (agents, MCP servers, hooks) only in trusted projects.")
    print("  Trust this one by starting `codex` here and accepting the prompt, or add")
    print("  to ~/.codex/config.toml:")
    print(f"      [projects.{_toml_str(str(project))}]")
    print('      trust_level = "trusted"')


class CodexAdapter(CliAdapter):
    id = "codex"
    display_name = "OpenAI Codex CLI"
    shared_outputs = frozenset({AGENTS_MD, AGENTS_SKILLS})
    agents_md_limit = 32 * 1024  # project_doc_max_bytes default

    def config_root(self, project: Path) -> Path:
        return project / ".codex"

    def supported_artifacts(self) -> set[str]:
        return {"rules", "skills", "commands", "agents", "hooks", "mcp"}

    def undeploy(self, project: Path, ctx: DeployContext) -> None:
        _deploy_agents(project, [])
        _deploy_mcp(project, [])
        _deploy_hooks(project, [])
        codex_dir = project / ".codex"
        if codex_dir.is_dir() and not any(codex_dir.iterdir()):
            codex_dir.rmdir()

    def deploy(self, project: Path, sel: Selections, ctx: DeployContext) -> DeployResult:
        agents = _deploy_agents(project, sel.agents)
        servers = _deploy_mcp(project, sel.mcp_servers)
        hooks = _deploy_hooks(project, sel.hooks)
        if servers:
            print(f"  Deployed {servers} MCP server(s) → {_CONFIG.as_posix()}")
        if (agents or servers or hooks) and not project_trusted(project):
            _print_trust_hint(project)
        if hooks:
            print("  Approve the foundry hooks once in Codex with /hooks "
                  "(Codex skips hooks until approved).")
        return DeployResult(ok=True)
